apiVersion: v1
kind: Service
metadata:
  name: geoapi
  labels:
    app: geoapi
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: geoapi
  ports:
    - name: http
      port: 80
      targetPort: http
{{- if eq (default "ClusterIP" .Values.service.type) "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 30080 }}
{{- end }}

