apiVersion: v1
kind: Service
metadata:
  name: geoapi
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: geoapi
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
