apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-restrict
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: postgres
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: geoapi
        - podSelector:
            matchLabels:
              job-name: geodata-import-largest
      ports:
        - port: 5432
          protocol: TCP
