{{- if and (not .Values.postgres.existingSecret) .Values.postgres.password }}
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
{{- end }}
