apiVersion: v1
kind: PersistentVolume
metadata:
  name: geodata-pv
spec:
  capacity:
    storage: 500Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /media/volume/aging-dams-data/geodata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geodata
  namespace: geo-risk-largest
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: manual
  resources:
    requests:
      storage: 500Gi
  volumeName: geodata-pv

