namespace: geo-risk-largest

image:
  repository: ghcr.io/iguide-postgis/geoapi
  tag: devfix 
  pullPolicy: IfNotPresent

postgres:
  image: postgis/postgis:16-3.4
  username: geo-iguide
  password: postgres-iguide 
  database: geodb_largest
  storage: 50Gi
  existingSecret: ""
  persistence:
   enabled: true
   existingClaim: postgis-pvc


# --- Import job settings (new) ---
importer:
  enabled: true
  # Use GHCR by default (works for you). You can change to docker.io/osgeo/gdal if preferred.
  image: ghcr.io/osgeo/gdal:ubuntu-small-3.10.1
  # Absolute path to the .gdb inside the mounted geodata PVC
  gdbPath: "/data/Utah Inundation Profiles/Utah Inundation Profiles.gdb"
  # How many times Kubernetes should retry the job
  backoffLimit: 0
  resources: {}   # e.g. { limits: { cpu: "2", memory: "4Gi" }, requests: { cpu: "500m", memory: "1Gi" } }

# Ensure this points at your existing PVC name
geodata:
  managePVC: true          # set to false when using an existing claim
  size: 500Gi
  storageClassName: manual
  volumeName: geodata-pv
  #existingClaim: ""        # set via CLI when managePVC=false
  existingClaim: geodata


geoapi:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi

ingress:
  enabled: true
  host: api.127.0.0.1.sslip.io

service:
  type: ClusterIP
  nodePort: null

